### ISSUE TITLE
code repeats

### ISSUE THREAD

**Issue by RobTillaart** [sparkfun/SparkFun_Clock_5P49V60_Arduino_Library#1]
IDEA:
Many methods in the lib repeat 4 times. 
I propose to use a parameter "clock" to make the interface smaller and easier to understand.

e.g

 ```
void SparkFun_5P49V60::setClockOneFreq(float freq)
...
```

==>

```
void SparkFun_5P49V60::setFreq(uint8_t clock, float freq)
{
  float division = (_vco_freq/2)/freq; 
  uint32_t int_portion = static_cast<uint32_t>(division);
  float decimal = fmod(division, int_portion);
  uint32_t frac_portion = static_cast<uint32_t>(decimal/pow(2.0,24.0));

  setIntDivOut(clock, int_portion);
  setFractDivFod(clock, frac_portion);

  clockControl(clock, ENABLE); 
}
```

**Comment by edspark** [comment]
Thanks for the suggestion. I did hem and haw about whether I wanted all of the functions to have a **clock** parameter or to do it as it is in the library now. I ultimately decided on the latter and I won't be making any changes to it in this regard. Come back anytime with more suggestions 👍!
