### ISSUE TITLE
Minor correction to messages

### ISSUE THREAD

**Issue by marcellosekoot** [sparkfun/SparkFun_Clock_5P49V60_Arduino_Library#2]
Hi,
This is a great example, I just wanted to point out that the print messages are from a previous version of the example and they do not reflect the settings used.
Thanks!

 Serial.println("Setting Internal Clock Frequency to 1600MHz.");    // actually 12MHz
 Serial.println("Setting Clock One Frequency to 16MHz.");    // actually 6MHz

**Comment by edspark** [comment]
Thanks for the post, I'll make sure to fix those! Woops =P

**Comment by edspark** [comment]
Fixed in release v1.01
